export const categories = [
  { emoji: '⏱️', label: 'New' },
  { emoji: '🔥', label: 'Spicy' },
  { emoji: '🍳', label: 'Breakfast' },
  { emoji: '🍔', label: 'Lunch' },
  { emoji: '🍝', label: 'Dinner' },
  { emoji: '🍰', label: 'High Cal' },
  { emoji: '🥗', label: 'Low Cal' },
  { emoji: '🍏', label: 'Healthy' },
  { emoji: '⚡', label: 'Fast' },
  { emoji: '🍔', label: 'Burgers' },
  { emoji: '🍕', label: 'Pizza' },
  { emoji: '🍣', label: 'Sushi' },
  { emoji: '🌮', label: 'Tacos' },
  { emoji: '🥞', label: 'Pancakes' },
  { emoji: '🥙', label: 'Wraps' },
  { emoji: '🍜', label: 'Noodles' },
  { emoji: '🥪', label: 'Sandwiches' },
  { emoji: '🍦', label: 'Desserts' },
  { emoji: '🍤', label: 'Seafood' },
  { emoji: '🍲', label: 'Soups' },
  { emoji: '🥘', label: 'Stews' },
  { emoji: '🍛', label: 'Curries' },
  { emoji: '🥓', label: 'Bacon' },
  { emoji: '🥩', label: 'Steak' },
  { emoji: '🍿', label: 'Snacks' },
  { emoji: '🥧', label: 'Pies' },
  { emoji: '🍗', label: 'Chicken' },
  { emoji: '🌯', label: 'Burritos' },
  { emoji: '🥤', label: 'Celebration' },
  { emoji: '🌱', label: 'Vegan' },
  { emoji: '🌾', label: 'Gluten-Free' }
];
